#!/usr/bin/env bash
# Install nginx web server
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
sudo service nginx reload
