#!/usr/bin/env bash
# Install nginx web server
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
newlines="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "/#error_page 404 \/404.html;/ a\\$newlines" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
