#!/usr/bin/env bash
# Install nginx web server
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
newlines="\terror_page 404 /custom_404.html;\n\tlocation = /custom_404 {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n\tlocation /redirect_me {\n\t\trewrite ^/redirect_me} https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "/#error_page 404 \/404.html;/ a\\$newlines" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
